#!/usr/bin/env bash
# [[file:testing.org::*Dagger wrapper for batch execution][Dagger wrapper for batch execution:1]]
export DAGGER_NO_NAG=1
export DARK=1
DAGGER_PATH="$(which -a dagger|grep -v /tests/|head -1)"
args=("$@")
if [ "${DAGGER_VERBOSE:-}" = "1" ]; then
    exec "$DAGGER_PATH" --progress=plain --silent "${args[@]}"
else
    exec "$DAGGER_PATH" --silent "${args[@]}" 2>/dev/null
fi
# Dagger wrapper for batch execution:1 ends here
