name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "0.20.3"
      - run: ./tangle.sh
      - run: ./test.sh
